#[derive(Debug)]
pub enum Instruction {
    Push,
    Fetch,
    Store,
    IF,
    Loop,
    Break,
    Return,
    Call,
    FPPlus,
    Add,
    Sub,
    Mul,
    Div,
    Mod,
    Not,
    And,
    OR,
    Xor,
    EQ,
    Neq,
    LT,
    Leq,
    GT,
    Geq,
    Pop,
    LShift,
    RShift,
    Unknown(i32)
}

impl Instruction {
    pub fn get_instruction(op_code: i32) -> Instruction {
        match op_code {
            1 => Instruction::Push,
            2 => Instruction::Fetch,
            3 => Instruction::Store,
            4 => Instruction::IF,
            5 => Instruction::Loop,
            6 => Instruction::Break,
            7 => Instruction::Return,
            8 => Instruction::Call,
            9 => Instruction::FPPlus,
            10 => Instruction::Add,
            11 => Instruction::Sub,
            12 => Instruction::Mul,
            13 => Instruction::Div,
            14 => Instruction::Mod,
            15 => Instruction::Not,
            16 => Instruction::And,
            17 => Instruction::OR,
            18 => Instruction::Xor,
            19 => Instruction::EQ,
            20 => Instruction::Neq,
            21 => Instruction::LT,
            22 => Instruction::Leq,
            23 => Instruction::GT,
            24 => Instruction::Geq,
            25 => Instruction::Pop,
            26 => Instruction::LShift,
            27 => Instruction::RShift,
            _ => Instruction::Unknown(op_code)
        }
    }
}